/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/authorization/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/authorization/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authorization/': {
      id: '/authorization/'
      path: '/authorization/'
      fullPath: '/authorization/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authorization/login': {
      id: '/authorization/login'
      path: '/authorization/login'
      fullPath: '/authorization/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/authorization/': typeof IndexRoute
  '/authorization/login': typeof LoginRoute
}

export interface FileRoutesByTo {
  '/authorization/': typeof IndexRoute
  '/authorization/login': typeof LoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/authorization/': typeof IndexRoute
  '/authorization/login': typeof LoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/authorization/' | '/authorization/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/authorization/' | '/authorization/login'
  id: '__root__' | '/authorization/' | '/authorization/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

